FROM ubuntu:18.04

MAINTAINER yucheng

RUN apt-get update

RUN apt-get install apt-utils -y
RUN apt-get install iptables -y
RUN apt-get install iputils-ping -y
RUN apt-get install net-tools -y
RUN apt-get install iproute2 -y
RUN apt-get install tcpdump -y
RUN apt-get install vim -y
RUN apt-get install sudo -y
RUN apt-get install isc-dhcp-server -y
RUN apt-get install isc-dhcp-client -y
RUN apt-get install libpcap-dev -y
RUN apt-get install build-essential -y
RUN apt-get install bridge-utils -y
RUN apt-get install tmux -y
RUN apt-get install netcat -y
